### ISSUE TITLE
BIP-72 Incompatibility for Non-backwards-compatible URI

### ISSUE THREAD

**Issue by ghost** [dashevo/dash-wallet#167]
Is it planed to fix BIP-72 incompatibility stated in https://github.com/HashEngineering/dash-wallet/blob/master/wallet/README.specs ?

Right now DASH-URIs like "dash?r=https://..." are not supported as seen on:
https://github.com/bitcoin/bips/blob/master/bip-0072.mediawiki

**Comment by HashEngineering** [comment]
We haven't tested BIP72 or BIP70 with this app and are not aware of any Dash Services that do.

It is not currently in our plan to get these working, but that could change.  If would be helpful if you could send us logs from the app or attach them here to document the errors associated with this feature.

**Comment by HashEngineering** [comment]
BIP70 support has been added and has been tested with AnyPay and DashDirect apps and services.
