### ISSUE TITLE
Locked when change from vertical to horizontal

### ISSUE THREAD

**Issue by margori** [dashevo/dash-wallet#195]
Using version 6.4.1, after unlocking the wallet I turn the phone from vertical to horizontal physical position and wallet is immediately locked, which is annoying.

I expect the wallet to be unlocked until some minutes in time, or screen get locked.

**Comment by HashEngineering** [comment]
PR #162 will address this issue of the wallet locking on screen rotation.

**Comment by HashEngineering** [comment]
This issue should be resolved with our Wallet Lock Timer feature.  This keeps the wallet unlocked for 3 minutes and screen rotations will not lock it.
