### ISSUE TITLE
disable fingerprint

### ISSUE THREAD

**Issue by gaby64** [dashevo/dash-wallet#213]
I have a broken fingerprint profile that keeps crashing the app, there is no evident way to disable it and reconfigure it

**Comment by HashEngineering** [comment]
Can you try going to Change PIN on the Safety Menu.  When you do this, it will allow you to reset your fingerprint.  Let us know if it works.

**Comment by gaby64** [comment]
that worked


On Jun. 17, 2019 at 12:53 a.m., <Hash Engineering Solutions<mailto:notifications@github.com>> wrote:


Can you try going to Change PIN on the Safety Menu. When you do this, it will allow you to reset your fingerprint. Let us know if it works.

**Comment by HashEngineering** [comment]
We have made changes in #232 that resolve this issue.  The app will ask the user to set up the fingerprint again if the fingerprints are invalid or have been modified.
