### ISSUE TITLE
Add setup to 'README.md' - CMake Error at dashj-bls/bls-signatures.cmake

### ISSUE THREAD

**Issue by AdamSHurwitz** [dashevo/dash-wallet#246]
# Expected
Run the Android _wallet_ module in Android Studio after cloning the repository.

# Observed

The following error occurs without running the required git commands first. Please add these git commands to the **README.md** setup instructions.

**Git Commands**
`git submodule init`
`git submodule update`

**Error**

> CMake Error at dashj-bls/bls-signatures.cmake:72 (add_subdirectory):
add_subdirectory given source "bls-signatures/contrib/relic" which is not
an existing directory.
Call Stack (most recent call first):
dashj-bls/CMakeLists.txt:53 (include)

**Comment by HashEngineering** [comment]
Thank you for pointing this out.  We have a pull request to update the documentation, but the build instructions don't have these commands.

https://github.com/HashEngineering/dash-wallet/pull/236/files

I will work on this in the coming week.

**Comment by HashEngineering** [comment]
#236 was merged, so this has been handled.
