### ISSUE TITLE
Add Confirm Dialog on Send

### ISSUE THREAD

**Issue by HashEngineering** [dashevo/dash-wallet#35]
It would be nice if there was an option to turn on a send confirmation dialog, so hitting send makes a box pop up that says something like "Do you really want to send x_address y Dash ($z)? Yes or No"

**Comment by sambarboza** [comment]
Is contribution welcome/allowed? If so I would like to work on this issue. Thanks!

**Comment by HashEngineering** [comment]
Yes, we welcome submissions.

**Comment by HashEngineering** [comment]
This has been addressed by the redesigned interface.
