### ISSUE TITLE
Add Unstoppable Domain Addresses

### ISSUE THREAD

**Issue by trymeouteh** [dashevo/dash-wallet#388]
Please add support for using unstoppable domains names as cryptocurrency addresses you can enter in to send payments to. Unstoppable domains allow you to send crypto to .zil and .crypto domain names.

**Comment by HashEngineering** [comment]
Does this support Dash?  Where is the SDK to resolve domains to addresses in Java?

**Comment by trymeouteh** [comment]
It does support Dash. I do not know how to do this in Java.

**Comment by HashEngineering** [comment]
We have no plans at this time to support unstoppable domain addresses.
