### ISSUE TITLE
sending funds internally to a dashpay address appears as loss of funds

### ISSUE THREAD

**Issue by dashameter** [dashevo/dash-wallet#664]
* B derives an address for A and sends funds to this address, e.g. yUCWj6aCMSPBibkKJfCWe74YFhmUmS13Gb

* A receives the funds

* If A sends funds to itself, the same address B derived for A, a few things are not handled correctly by android wallet giving the impression of loss of funds

The amount is displayed correctly in the confirmation screen
![1](https://user-images.githubusercontent.com/57665975/115872257-c9430280-a46b-11eb-9060-96082e848a5c.png)

In the success screen the amount is lost, only the network fee is shown. Also the Sent to field shows an outgoing transaction to B instead of an internal transaction to A (owning the key to the address).

![2](https://user-images.githubusercontent.com/57665975/115872302-d8c24b80-a46b-11eb-9c80-507c98e19112.png)

The transaction field shows a 0 Dash transaction instead of the internal wallet transaction of 0.1111

![3](https://user-images.githubusercontent.com/57665975/115872381-f1cafc80-a46b-11eb-8339-8960d58e6784.png)

![4](https://user-images.githubusercontent.com/57665975/115872394-f55e8380-a46b-11eb-83cf-fd9873d9ae71.png)

Example transaction on testnet:
https://testnet-insight.dashevo.org/insight/tx/8b47ea40729b0d5d527585626c6615957e5894bfb840487e4375502ba9ee9d43

**Comment by HashEngineering** [comment]
Thank you for this report.  We have added it to our backlog.

**Comment by HashEngineering** [comment]
This was resolved here:
https://github.com/dashevo/dash-wallet/pull/678

And the fix will be available in the next release of the DashPay Testnet app (v4.4 or higher).
