### ISSUE TITLE
Release 7.2.5

### ISSUE THREAD

**Issue by socram8888** [dashevo/dash-wallet#683]
Hello! Just a friendly reminder that there doesn't seem to be a 7.2.5 release here on GitHub matching the current version (since May, 24th) available on Google Play.

**Comment by HashEngineering** [comment]
Thanks for the reminder, it is now published here:
https://github.com/dashevo/dash-wallet/releases/tag/v7.2.5

**Comment by socram8888** [comment]
Perfect, many thanks!
