### ISSUE TITLE
Two Errors Building on a Mac Book. 

### ISSUE THREAD

**Issue by ghost** [dashevo/dash-wallet#72]
Hey Guys, 

I Got Two Errors Trying to Build The Project on My Mac Book. 

The First was an Error with WindowsMMapHack.java. 

![screen shot 2018-01-31 at 5 20 17 am](https://user-images.githubusercontent.com/32527124/35619282-8432818c-064b-11e8-8a86-90c6be418b9f.png)

The Second was with build.gradle.

![screen shot 2018-01-31 at 5 50 56 am](https://user-images.githubusercontent.com/32527124/35619314-9fcb4bd6-064b-11e8-85c8-886a1f555279.png)

I Followed The Steps Listed Here:

https://github.com/HashEngineering/dash-wallet

Any Assistance would be Appreciated.

Thank you.

**Comment by HashEngineering** [comment]
I haven't seen this error before, but haven't built on a Mac.
